# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Liverpool' do
  use_frameworks!

  # Pods for Liverpool
  pod 'SDWebImage', '~> 4.0'
  pod 'Alamofire', '~> 4.6'
  pod 'SwiftSpinner'

end
